#!/usr/bin/env python3
"""Keep packaged Python and compiled Swift study interviews identical to the seed."""
from pathlib import Path
import argparse

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
texts = {}
for intent in ('conceptStudy', 'agentComparison', 'multiAgent'):
    name = f'study-{intent}.md'
    data = (root / 'WorkspaceSeed/prompts/study-interviews' / name).read_bytes()
    texts[intent] = data.decode().rstrip('\n')
    target = root / 'Server/steerlab_server/experiment/seed/prompts/study-interviews' / name
    if args.write:
        target.write_bytes(data)
    else:
        assert target.read_bytes() == data, f'Regenerate {target}'
swift = '// Generated by scripts/ci/check-study-interviews.py --write. Edit WorkspaceSeed study interviews.\n'
swift += 'enum StudyInterviewText {\n'
for intent, text in texts.items():
    assert '"""#' not in text
    swift += f'    static let {intent} = #"""\n' + '\n'.join('    ' + line if line else '' for line in text.splitlines()) + '\n    """#\n'
swift += '}\n'
target = root / 'Sources/ExperimentKit/StudyInterviewText.swift'
if args.write:
    target.write_text(swift)
else:
    assert target.read_text() == swift, 'Regenerate Swift study interviews'
print('Study interview sources match both packaged clients.')
