#!/usr/bin/env python3
"""Generate the shared science declarations from small per-operation specs.

No scientific owner bodies or audit baselines are generated here.
"""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]


def artifacts():
    source = ROOT / 'docs/techniques'
    metadata = json.loads((source / 'registry.json').read_text())
    specs = [json.loads(p.read_text()) for p in sorted((source / 'operations').glob('*.json'))]
    ids = [s['catalog']['id'] for s in specs]
    assert len(ids) == len(set(ids)), 'Duplicate operation ID'
    assert len({s['order'] for s in specs}) == len(specs), 'Duplicate catalog ordering'
    bindings, special, roles = {}, [], {}
    for spec in specs:
        name = spec['catalog']['id']
        assert (source / 'operations' / (name + '.json')).is_file(), 'ID/filename mismatch'
        assert spec['schemaVersion'] == 1
        assert set(spec) <= {'schemaVersion', 'order', 'catalog', 'interview', 'interviewOrder', 'binding', 'inputRoleProfile', 'inputRoles'}
        if 'interview' not in spec:
            assert 'binding' not in spec, 'Execution binding requires an interview'
            continue
        assert spec['interview']['id'] == name
        assert spec['interview']['method'] == spec['catalog']['method']
        binding = spec['binding']
        if 'special' in binding:
            assert binding == {'special': name}
            special.append(name)
        else:
            assert set(binding) == {'module', 'config_class', 'function', 'compute'}
            assert binding['compute'] in {'cpu', 'gpu'}
            assert all(isinstance(v, str) and v for v in binding.values())
            bindings[name] = binding
        roles[name] = {**metadata['inputRoleProfiles'][spec['inputRoleProfile']], **spec['inputRoles']}
        assert all(v in {'artifact', 'artifacts', 'file', 'trees', 'lens'} for v in roles[name].values())
    interviews = sorted((s for s in specs if 'interview' in s), key=lambda s: s['interviewOrder'])
    assert len({s['interviewOrder'] for s in interviews}) == len(interviews)
    catalog = {**metadata['catalog'], 'operations': [s['catalog'] for s in sorted(specs, key=lambda s: s['order'])]}
    workflows = {**metadata['workflows'], 'operations': [s['interview'] for s in interviews]}
    generated = '# Generated by scripts/ci/check-operation-specs.py --write. Edit docs/techniques.\n'
    # Python literals (not JSON null/true) keep this small, importable and free of file I/O.
    generated += 'BINDINGS = ' + repr(dict(sorted(bindings.items()))) + '\n'
    generated += 'SPECIAL = frozenset(' + repr(sorted(special)) + ')\n'
    # Deduplicate the shared vocabulary while permitting per-operation overrides.
    profiles = metadata['inputRoleProfiles']
    generated += 'INPUT_ROLE_PROFILES = ' + repr(profiles) + '\n'
    generated += 'INPUT_ROLES = {\n'
    for spec in interviews:
        generated += '    ' + repr(spec['catalog']['id']) + ': {**INPUT_ROLE_PROFILES[' + repr(spec['inputRoleProfile']) + '], **' + repr(spec['inputRoles']) + '},\n'
    generated += '}\n'
    return {
        'WorkspaceSeed/prompts/method-guides/catalog.json': json.dumps(catalog, indent=2, ensure_ascii=False) + '\n',
        'WorkspaceSeed/prompts/method-guides/workflows.json': json.dumps(workflows, indent=2, ensure_ascii=False) + '\n',
        'Server/steerlab_server/experiment/operation_bindings.py': generated,
    }


def main():
    parser = argparse.ArgumentParser(description=__doc__)
    parser.add_argument('--write', action='store_true')
    args = parser.parse_args()
    for name, text in artifacts().items():
        path = ROOT / name
        if args.write: path.write_text(text)
        else: assert path.read_text() == text, 'Regenerate ' + name
    print('Operation specifications match catalog, interviews, execution bindings and input roles.')


if __name__ == '__main__': main()
