#!/usr/bin/env python3
"""Generate/gate the Python source identity expected by the compiled Mac client."""
import argparse
from pathlib import Path
import sys

ROOT = Path(__file__).resolve().parents[2]
sys.path.insert(0, str(ROOT / 'Server'))
from steerlab_server.client.runtime_identity import source_sha256

parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
text = ('// Generated by scripts/ci/check-python-client-identity.py --write.\n'
        'enum PythonClientIdentity {\n'
        f'    static let sourceSHA256 = "{source_sha256()}"\n'
        '}\n')
path = ROOT / 'Sources/ExperimentKit/PythonClientIdentity.swift'
if args.write:
    path.write_text(text)
else:
    assert path.read_text() == text, 'Regenerate the Python client identity and rebuild both Mac targets.'
print('Compiled Mac client identity matches shipped Python sources and seeds.')
