#!/usr/bin/env python3
"""Generate/gate method guidance shared by packaged Python and compiled Swift."""
from pathlib import Path
import argparse
import json

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
source = root / 'WorkspaceSeed/prompts/method-guides'
catalog = json.loads((source / 'catalog.json').read_text())
assert catalog['schemaVersion'] == 1
assert len({m['id'] for m in catalog['methods']}) == len(catalog['methods'])
assert len({o['id'] for o in catalog['operations']}) == len(catalog['operations'])
ids = {m['id'] for m in catalog['methods']}
assert all(o['method'] in ids for o in catalog['operations'])
files = ['catalog.json', 'workflows.json'] + [m['guide'] for m in catalog['methods']]
assert set(files) == {p.name for p in source.iterdir() if p.is_file()}
packaged = root / 'Server/steerlab_server/experiment/seed/prompts/method-guides'
if args.write:
    packaged.mkdir(parents=True, exist_ok=True)
texts = {}
for name in files:
    data = (source / name).read_bytes()
    texts[name] = data.decode('utf-8')
    if args.write:
        (packaged / name).write_bytes(data)
    else:
        assert (packaged / name).read_bytes() == data, f'Regenerate {name}'
# A single encoded dictionary keeps escaping mechanical and preserves final LF.
swift = '// Generated by scripts/ci/check-science-resources.py --write. Edit WorkspaceSeed method guides.\n'
swift += 'enum ScienceResourceText {\n    static let filesJSON = #"""\n'
swift += '\n'.join('    ' + line for line in json.dumps(texts, ensure_ascii=False, sort_keys=True, indent=2).splitlines())
swift += '\n    """#\n}\n'
assert '"""#' not in json.dumps(texts, ensure_ascii=False)
target = root / 'Sources/ExperimentKit/ScienceResourceText.swift'
if args.write:
    target.write_text(swift)
else:
    assert target.read_text() == swift, 'Regenerate Swift science resources'
print('Science catalog and method guides match both packaged clients.')

from science_cli_census import check_catalog
import json
check_catalog(json.loads((Path(__file__).resolve().parents[2] / "WorkspaceSeed/prompts/method-guides/catalog.json").read_text()), (Path(__file__).resolve().parents[2] / "Server/steerlab_server/cli.py").read_text())

import sys
sys.path.insert(0, str(Path(__file__).resolve().parents[2] / 'Server'))
from steerlab_server.api.route_roles import CENSUS
from science_cli_census import check_actions
check_actions(json.loads((Path(__file__).resolve().parents[2] / 'WorkspaceSeed/prompts/method-guides/catalog.json').read_text()), CENSUS)

from steerlab_server.experiment.managed_methods import OPERATIONS
workflows = json.loads((source / 'workflows.json').read_text())
assert {o['id'] for o in workflows['operations']} == OPERATIONS
assert len(workflows['operations']) == len(OPERATIONS)
for operation in workflows['operations']:
    assert operation['method'] == next(o['method'] for o in catalog['operations'] if o['id'] == operation['id'])
    assert operation['claimBoundary'] and operation['questions']
    assert len({f['id'] for f in operation['fields']}) == len(operation['fields'])
    assert all(f['kind'] in {'text','integer','number','boolean','integers','numbers','artifact','artifacts','file','files','fileRef','documentFile'} for f in operation['fields'])
print('Shared interviews cover every managed method with distinct catalog categories.')

# The documented substrate table covers this same operation census. It informs
# researchers; it is never consulted to admit or reject an execution request.
import subprocess
subprocess.run([sys.executable, str(root / 'scripts/ci/check-substrates.py'),
                *(['--write'] if args.write else [])], check=True)

# Scope descriptions use one maintained vocabulary across execution engines.
subprocess.run([sys.executable, str(root / 'scripts/ci/check-intervention-scopes.py'),
                *(['--write'] if args.write else [])], check=True)
