#!/usr/bin/env python3
"""Generate/gate the headline-outcome order shared by Python, Swift, and the results explorer.

The one source is Server/steerlab_server/client/resources/headline-outcomes.json.
Python reads it directly. This script writes the compiled Swift copy and the
results explorer's copy from it, or (without --write) fails when either is stale.
"""
from pathlib import Path
import argparse
import json

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()

source = root / 'Server/steerlab_server/client/resources/headline-outcomes.json'
data = json.loads(source.read_text(encoding='utf-8'))

# The shape every reader relies on.
assert data['schemaVersion'] == 1
tiers = [tier['id'] for tier in data['tiers']]
assert len(tiers) == len(set(tiers)) and data['unlistedTier'] == tiers[-1]
names = [entry['name'] for entry in data['outcomes']]
assert len(names) == len(set(names))
for entry in data['outcomes']:
    assert entry['match'] in ('exact', 'prefix', 'suffix'), entry
    assert entry['tier'] in tiers[:-1], entry
    assert entry['source'] in ('analysisRows', 'evaluationReport'), entry
    assert entry['plain'], entry
    # Every requirement has its plain-words "needs" line (empty for the two
    # that need nothing a study could add).
    assert entry['requires'] in data['requirements'], entry
# Entries are grouped by tier, in tier order.
positions = [tiers.index(entry['tier']) for entry in data['outcomes']]
assert positions == sorted(positions), 'List outcomes tier by tier, in tier order.'
assert set(data['rules']) == {'declared', 'defaultOrder'}

pretty = json.dumps(data, ensure_ascii=False, indent=2)
assert '"""#' not in pretty and '`' not in pretty and '${' not in pretty

swift = '// Generated by scripts/ci/check-headline-outcomes.py --write. Edit Server/steerlab_server/client/resources/headline-outcomes.json.\n'
swift += 'enum HeadlineOutcomeData {\n    static let json = #"""\n'
swift += '\n'.join('    ' + line for line in pretty.splitlines())
swift += '\n    """#\n}\n'

typescript = '// Generated by scripts/ci/check-headline-outcomes.py --write. Edit Server/steerlab_server/client/resources/headline-outcomes.json.\n'
typescript += 'export const headlineOutcomeData = ' + pretty + ';\n'

targets = {
    root / 'Sources/ExperimentKit/HeadlineOutcomeData.swift': swift,
    root / 'results-explorer/app/lib/headlineOutcomes.generated.ts': typescript,
}
for target, text in targets.items():
    if args.write:
        target.write_text(text, encoding='utf-8')
    else:
        assert target.exists() and target.read_text(encoding='utf-8') == text, \
            f'Regenerate {target.relative_to(root)}: python3 scripts/ci/check-headline-outcomes.py --write'
print('Headline outcome order matches the compiled Swift and results explorer copies.')
