#!/usr/bin/env python3
"""Generate/gate the complete seed inventory and agent contract for both clients."""
import argparse
import json
from pathlib import Path

ROOT = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
resources = ROOT / 'Server/steerlab_server/client/resources'
manifest = json.loads((resources / 'workspace.json').read_text())
files = manifest['seedFiles']
assert len(files) == len(set(files))
seed = ROOT / 'WorkspaceSeed'
actual = {p.relative_to(seed).as_posix() for p in seed.rglob('*') if p.is_file() and not any(part.startswith('.') for part in p.relative_to(seed).parts)}
assert set(files) == actual, ('Workspace seed inventory differs', set(files) ^ actual)
packaged = ROOT / 'Server/steerlab_server/experiment/seed'
for name in files:
    assert not Path(name).is_absolute() and '..' not in Path(name).parts
    source = seed / name
    target = packaged / name
    if args.write:
        target.parent.mkdir(parents=True, exist_ok=True)
        target.write_bytes(source.read_bytes())
    else:
        assert target.read_bytes() == source.read_bytes(), 'Regenerate packaged seed: ' + name
body = '\n'.join(line for line in (ROOT / 'docs/AGENTS-WORKSPACE-DRAFT.md').read_text().splitlines() if not line.strip().startswith('<!--')).strip() + '\n'
agent = resources / 'agent-guide.md'
if args.write:
    agent.write_text(body)
else:
    assert agent.read_text() == body, 'Regenerate packaged agent guide'
values = dict(seedFiles=files, promptDirectories=[p.removeprefix('prompts/') for p in manifest['directories'] if p.startswith('prompts/')],
              gitignore=manifest['gitignore'], markerTemplate=(resources / 'workspace-marker.md').read_text(), agentBody=body)
swift = '// Generated by scripts/ci/check-workspace-bootstrap.py --write.\nimport Foundation\n\nenum WorkspaceBootstrapText {\n'
for name, value in values.items():
    encoded = json.dumps(value, ensure_ascii=False)
    assert '"""#' not in encoded
    if isinstance(value, list):
        swift += f'    static let {name}: [String] = {encoded}\n'
    else:
        # Decode JSON strings to avoid a second escaping convention.
        swift += f'    static let {name} = try! JSONDecoder().decode(String.self, from: Data(#"""\n        {encoded}\n        """#.utf8))\n'
swift += '}\n'
target = ROOT / 'Sources/ExperimentKit/WorkspaceBootstrapText.swift'
if args.write:
    target.write_text(swift)
else:
    assert target.read_text() == swift, 'Regenerate compiled workspace resources'
print('Complete workspace seed, agent guide and compiled resources match.')
