#!/usr/bin/env python3
"""Compile pinned sampling dependency identity into run provenance."""
import argparse
import json
from pathlib import Path

root = Path(__file__).resolve().parents[2]
parser = argparse.ArgumentParser(description=__doc__)
parser.add_argument('--write', action='store_true')
args = parser.parse_args()
pins = {p['identity']: p['state'] for p in json.loads((root / 'Package.resolved').read_text())['pins']
        if p['identity'] in {'mlx-swift', 'mlx-swift-lm', 'swift-transformers'}}
rows = ',\n'.join('        ' + json.dumps(name) + ': [' + ', '.join(
    json.dumps(k) + ': ' + json.dumps(v) for k, v in sorted(pin.items())) + ']'
    for name, pin in sorted(pins.items()))
text = '// Generated by scripts/ci/check-sampling-dependencies.py --write.\n'
text += 'enum SamplingDependencies {\n    static let pins: [String: [String: String]] = [\n' + rows + '\n    ]\n}\n'
target = root / 'Sources/ExperimentKit/SamplingDependencies.swift'
if args.write:
    target.write_text(text)
else:
    assert target.read_text() == text, 'Regenerate sampling dependency identity'
print('Sampling dependency identity matches Package.resolved.')
