import Foundation
import MLX

// =============================================================================
// Where this binary is installed, and what it can therefore do
// (WP0-AGENT-SURFACE-AUDIT §6, §7 step 12).
//
// The audit measured the runtime dependency surface and found it far narrower
// than the work plan assumed: the executable statically links the entire
// package graph (zero `@rpath` dylibs), so the ONLY runtime dependency is the
// Metal shader library, and only for GPU verbs. MLX's lookup order checks a
// COLOCATED `mlx.metallib` first (`device.cpp` `load_colocated_library`), so an
// install that puts the shader library beside the executable needs no
// `DYLD_FRAMEWORK_PATH` at all — which is what makes a plain
// `~/.local/libexec/steerlab/` layout sufficient.
//
// This type is what `steerlab-cli install version|stamp|verify` reports and
// acts on. It exists because three questions have to be answerable from the
// installed binary itself, with no checkout to read:
//
//   1. WHICH BUILD IS THIS? — `SteerLabVersion.current`, which prefers the
//      stamped `resource-manifest.json` written at install time over a live
//      `git rev-parse` in a checkout that may not exist.
//   2. WILL A GPU VERB WORK? — is `mlx.metallib` colocated, or is the process
//      relying on the developer `DYLD_FRAMEWORK_PATH` fallback?
//   3. IS THE INSTALLED TREE INTACT? — `ResourceManifest.verify(against:)`
//      over the install root. §6.2 asked for exactly this reuse; until now the
//      manifest was generated by nothing but tests.
//
// **Where verification lives, decided here.** Hashing a 147 MB executable is
// not free, and `--version` is the verb a caller runs when something is
// already confusing. So `install version` REPORTS whether the tree is stamped
// and names the check; `install verify` performs it. `scripts/install-cli.sh
// --verify` shells out to that verb rather than re-implementing SHA-256 in the
// shell, so there is exactly one hasher.
//
// Nothing here is Mac-distribution Phase B: no code signing, no `.app`, no
// embedded resource families. An installed R1 binary that needs workspace seed
// data still resolves it through `CodeResources`, which finds the developer
// checkout when one exists on the machine and fails closed with a plain
// sentence when it does not.
// =============================================================================

/// What the install layout looks like from inside the running process.
public struct InstallProvenance: Sendable {

    /// How this executable is deployed.
    public enum Shape: String, Sendable, Codable {
        /// A stamped install: a `resource-manifest.json` sits beside the
        /// executable, so the build's identity travels with it.
        case installed
        /// A build product run in place (the checkout's
        /// `.deriveddata.nosync/Build/Products/Debug/steerlab-cli`, or a copy
        /// that was never stamped).
        case buildProduct
    }

    /// The file name the installer gives the colocated Metal shader library.
    /// MLX probes `current_binary_dir()/mlx.metallib` FIRST, before any bundle
    /// lookup — the fact the whole layout rests on.
    public static let metallibName = "mlx.metallib"

    /// The manifest file name. Deliberately the name `CodeResources.Family
    /// .buildManifest` already resolves, so `SteerLabVersion.current` picks up
    /// the stamped version with no further wiring: `Bundle.main.resourceURL`
    /// of a bare command-line executable IS its own directory.
    public static let manifestName = CodeResources.Family.buildManifest.rawValue

    /// The R1 install carries no Python payload — the server stays an editable
    /// checkout (audit §6.2), and saying so is better than stamping a version
    /// number for something that is not there.
    public static let unbundledServerVersion = "unbundled"

    /// The app↔server protocol version this build speaks.
    public static let protocolVersion = 1

    /// The running executable.
    public let executable: URL
    /// The directory the executable lives in — the install root, and the
    /// directory MLX resolves `mlx.metallib` against.
    public let root: URL
    public let shape: Shape
    /// `swift-app <version>[+<sha>]`.
    public let engineVersion: String
    /// The stamped manifest, when the tree carries one.
    public let manifest: ResourceManifest?
    /// The colocated shader library, when it is there.
    public let metallib: URL?
    /// `DYLD_FRAMEWORK_PATH` as inherited — the developer fallback. Reported
    /// because a GPU verb that works only because this is set is not evidence
    /// that the install works.
    public let dyldFrameworkPath: String?
    /// How immutable program resources resolve in this process.
    public let resourceMode: CodeResources.Mode
    /// The developer checkout, when this machine still has one.
    public let checkoutRoot: URL?

    // MARK: Resolution

    /// Read the layout of the running process. Never throws: a version query
    /// that fails because something is missing has answered the wrong
    /// question — absence is the answer.
    public static func resolve(
        executable: URL? = nil,
        environment: [String: String] = ProcessInfo.processInfo.environment
    ) -> InstallProvenance {
        let fm = FileManager.default
        let exe =
            executable
            ?? Bundle.main.executableURL?.resolvingSymlinksInPath()
            ?? URL(filePath: CommandLine.arguments.first ?? "steerlab-cli")
                .standardizedFileURL
        let root = exe.deletingLastPathComponent()

        let manifestURL = root.appending(component: manifestName)
        let manifest = fm.fileExists(atPath: manifestURL.path)
            ? try? ResourceManifest.load(from: manifestURL) : nil

        let metallibURL = root.appending(component: metallibName)
        let metallib = fm.fileExists(atPath: metallibURL.path) ? metallibURL : nil

        return InstallProvenance(
            executable: exe, root: root,
            shape: manifest == nil ? .buildProduct : .installed,
            engineVersion: SteerLabVersion.current,
            manifest: manifest, metallib: metallib,
            dyldFrameworkPath: environment["DYLD_FRAMEWORK_PATH"],
            resourceMode: CodeResources.mode,
            checkoutRoot: CodeResources.developerCheckoutRoot)
    }

    /// True when a GPU verb can find its shaders from the install alone.
    /// `DYLD_FRAMEWORK_PATH` is deliberately NOT part of this: the audit's
    /// §6.1 claim under test is that the colocated copy suffices, and a
    /// property that answered "yes" because the developer environment was
    /// inherited would test nothing.
    public var metallibColocated: Bool { metallib != nil }

    /// The shim that would front this install under the §6.2 layout, when it
    /// exists and actually points here. Never invented: a reported shim that
    /// runs a different binary is worse than none.
    public var shim: URL? {
        let candidate = root
            .deletingLastPathComponent()  // libexec/
            .deletingLastPathComponent()  // ~/.local/
            .appending(components: "bin", "steerlab")
        guard
            let text = try? String(contentsOf: candidate, encoding: .utf8),
            text.contains(executable.lastPathComponent)
        else { return nil }
        return candidate
    }

    // MARK: Reporting

    /// The human report — the body of `install version`.
    public var report: String {
        var lines: [String] = ["steerlab-cli — \(engineVersion)"]
        func row(_ label: String, _ value: String) {
            let padding = String(repeating: " ", count: max(1, 14 - label.count))
            lines.append("  \(label)\(padding)\(value)")
        }
        row("layout", shape == .installed ? "installed" : "build product (unstamped)")
        row("executable", executable.path)
        if let metallib {
            row(
                "metal", "\(metallib.lastPathComponent) colocated — GPU verbs "
                    + "need no DYLD_FRAMEWORK_PATH")
        } else if let dyld = dyldFrameworkPath {
            row("metal", "no colocated \(Self.metallibName); relying on "
                + "DYLD_FRAMEWORK_PATH=\(dyld)")
        } else {
            row("metal", "no colocated \(Self.metallibName) and no "
                + "DYLD_FRAMEWORK_PATH — GPU verbs will refuse to load shaders")
        }
        if let manifest {
            var stamp = "\(Self.manifestName): \(manifest.files.count) file(s), "
                + "app \(manifest.appVersion)"
            if let revision = manifest.sourceRevision, !revision.isEmpty {
                stamp += "+\(revision)"
            }
            row("manifest", stamp)
            row("integrity", "not checked here — run: steerlab-cli install verify")
        } else {
            row("manifest", "none — this tree was never stamped")
        }
        switch resourceMode {
        case .developer:
            row(
                "resources", "developer checkout at "
                    + (checkoutRoot?.path ?? "(unknown)"))
        case .release:
            row("resources", "release mode — bundled resources only")
        }
        // WP2: family-by-family resolution, and where bucket B (the writable
        // checkout the local Python engine and analysis venvs need) resolved.
        // Resolution only — hashing stays behind `install verify`.
        let check = CodeResources.selfCheck()
        row("families", check.summaryDetail)
        lines.append(contentsOf: check.report.dropFirst())
        if let shim { row("shim", shim.path) }
        return lines.joined(separator: "\n") + "\n"
    }

    /// The same facts as data. Absent is absent — a key is omitted rather
    /// than carrying an empty string, so a caller's `if let` means something.
    public var payload: [String: JSONValue] {
        var payload: [String: JSONValue] = [
            "version": .string(engineVersion),
            "layout": .string(shape.rawValue),
            "executable": .string(executable.path),
            "installRoot": .string(root.path),
            "metallibColocated": .bool(metallibColocated),
            "resourceMode": .string(resourceMode.rawValue),
            "manifestStamped": .bool(manifest != nil),
            "protocolVersion": .number(Double(Self.protocolVersion)),
        ]
        if let metallib { payload["metallib"] = .string(metallib.path) }
        if let dyldFrameworkPath {
            payload["dyldFrameworkPath"] = .string(dyldFrameworkPath)
        }
        if let checkoutRoot { payload["checkoutRoot"] = .string(checkoutRoot.path) }
        if let shim { payload["shim"] = .string(shim.path) }
        if let manifest {
            var stamp: [String: JSONValue] = [
                "appVersion": .string(manifest.appVersion),
                "serverVersion": .string(manifest.serverVersion),
                "fileCount": .number(Double(manifest.files.count)),
            ]
            if let revision = manifest.sourceRevision {
                stamp["sourceRevision"] = .string(revision)
            }
            payload["manifest"] = .object(stamp)
        }
        return payload
    }

    // MARK: Stamping

    /// Entries whose presence means the caller pointed `install stamp` at a
    /// BUILD directory rather than an install root. Stamping DerivedData
    /// would hash a gigabyte of object files and, worse, would make
    /// `SteerLabVersion.current` read a manifest nobody meant to create.
    private static let buildDirectorySuffixes = [".o", ".swiftmodule", ".xctest"]

    /// Write `resource-manifest.json` over the install root: every file
    /// beside the executable, hashed, plus the build identity.
    ///
    /// The manifest never lists ITSELF. On a first stamp that falls out of the
    /// ordering (it is written after the walk); on a RE-stamp it does not, and
    /// the previous manifest has to be removed before the walk — otherwise the
    /// new manifest records the OLD manifest's hash, which the very next line
    /// overwrites, and `install verify` then reports a permanent mismatch
    /// against the file it just wrote. `reStampingIsIdempotent` is the test.
    /// `verify(against:)` treating unlisted files on disk as legal is what
    /// makes the omission safe.
    @discardableResult
    public static func stamp(
        root: URL, appVersion: String = SteerLabVersion.version,
        sourceRevision: String? = nil
    ) throws -> ResourceManifest {
        let fm = FileManager.default
        let names = (try? fm.contentsOfDirectory(atPath: root.path)) ?? []
        if let offender = names.first(where: { name in
            buildDirectorySuffixes.contains { name.hasSuffix($0) }
        }) {
            throw ExperimentError(
                reason: "\(root.path) looks like a build directory (it contains "
                    + "\(offender)), not an install root — stamping it would "
                    + "hash the whole build. Install first: "
                    + "scripts/install-cli.sh")
        }
        let manifestURL = root.appending(component: manifestName)
        try? fm.removeItem(at: manifestURL)
        let manifest = try ResourceManifest.generate(
            over: root, appVersion: appVersion,
            serverVersion: unbundledServerVersion,
            protocolVersion: protocolVersion, sourceRevision: sourceRevision)
        try manifest.write(to: manifestURL)
        return manifest
    }

    // MARK: Verification

    /// Dispatch one trivial Metal kernel and report which GPU ran it.
    ///
    /// This is the instrument for the §6.1 claim the audit left UNVERIFIED:
    /// that a colocated `mlx.metallib` is enough, with no
    /// `DYLD_FRAMEWORK_PATH`. Every CPU-only verb passes whether the shader
    /// library is there or not, so only a kernel dispatch can answer it — and
    /// unlike a smoke test it needs no model weights, so the check runs on a
    /// machine with an empty Hugging Face cache.
    ///
    /// A missing shader library is fatal inside MLX's C++ (it does not surface
    /// as a Swift error), so the honest contract is: this returns a sentence
    /// when the shaders loaded, and the process does not survive to return
    /// anything when they did not.
    public static func probeMetalShaders() -> String {
        let probe = MLXArray([1, 2, 3, 4] as [Float])
        let total = using(device: .gpu) { () -> Float in
            let squared = probe * probe
            eval(squared)
            return squared.sum().item(Float.self)
        }
        let info = GPU.deviceInfo()
        return "Metal shaders loaded on \(info.architecture); a GPU kernel "
            + "returned \(Int(total))"
    }

    /// Check the installed tree against its stamp. The ONE hasher — the
    /// installer's `--verify` mode runs this verb rather than re-deriving
    /// SHA-256 in shell.
    public func verifyInstalledTree() throws -> [ResourceManifest.Problem] {
        guard let manifest else {
            throw ExperimentError(
                reason: "\(root.path) carries no \(Self.manifestName), so there "
                    + "is nothing to verify against")
        }
        return manifest.verify(against: root)
    }
}
