import Foundation
import SteeringKit

/// Manifest-epoch stamps on run directories, and the guard that reads them.
///
/// A run directory records WHICH manifest epoch produced it, so a later verb
/// can refuse to treat a pre-edit run as evidence for a post-edit manifest.
/// The stamp lives in `experiment-hash.txt`, with the canonical `config.json`
/// `experimentHash` as the fallback for runs written before that file existed.
///
/// Cross-engine twin of `Server/steerlab_server/experiment/run_epoch.py`. The
/// guard is deliberately PER-ENGINE — canonicalization differs between
/// substrates, so a run is checked on the engine that produced it.
public enum RunEpoch {

    /// The run's manifest-epoch stamp, or nil when absent/unreadable.
    public static func stampedExperimentHash(_ runDirectory: URL) -> String? {
        if let text = try? String(
            contentsOf: runDirectory.appending(component: "experiment-hash.txt"),
            encoding: .utf8)
        {
            let trimmed = text.trimmingCharacters(in: .whitespacesAndNewlines)
            if !trimmed.isEmpty { return trimmed }
        }
        guard
            let data = try? Data(
                contentsOf: runDirectory.appending(component: "config.json")),
            let object = try? JSONSerialization.jsonObject(with: data)
                as? [String: Any],
            let value = object["experimentHash"] as? String,
            !value.isEmpty
        else { return nil }
        return value
    }

    /// The manifest snapshot a run carries, decoded — the only epoch
    /// evidence that means the same thing on both engines.
    public static func snapshot(_ runDirectory: URL) -> ExperimentManifest? {
        guard
            let data = try? Data(
                contentsOf: runDirectory.appending(component: "experiment.json"))
        else { return nil }
        return try? JSONDecoder().decode(ExperimentManifest.self, from: data)
    }

    /// The ONE result of an epoch check, parallel to the Python twin's
    /// ``(refusal, unverified, measurement_drift)`` triple.
    ///
    /// Carrying the refusal rather than throwing keeps the error TYPE with
    /// the caller: `ExperimentTasks` raises `ExperimentError`, `promote`
    /// raises its own, and neither has to catch and re-wrap the other's.
    /// The two acceptance flags are OBLIGATIONS on the caller, not
    /// pleasantries: an accepted-but-flagged run must be logged loudly and
    /// stamped into the caller's own output (`epochUnverified`,
    /// `measurementDrift`) — tolerated is never silent.
    public struct Check: Sendable, Equatable {
        /// Non-nil = refuse, with this message.
        public var refusal: String?
        /// An UNSTAMPED legacy run accepted under `allowUnverified`; the
        /// caller stamps `epochUnverified: true`.
        public var unverified: Bool
        /// A hash mismatch accepted under `tolerateMeasurementDrift`
        /// because every drifted field is measurement-side; the caller
        /// stamps `measurementDrift` with this changed-fields description.
        public var measurementDrift: String?

        public init(
            refusal: String? = nil,
            unverified: Bool = false,
            measurementDrift: String? = nil
        ) {
            self.refusal = refusal
            self.unverified = unverified
            self.measurementDrift = measurementDrift
        }

        /// The run belongs to this epoch outright — nothing to stamp.
        public static let eligible = Check()
    }

    /// Manifest fields that cannot affect a single generated byte of a
    /// source run: they configure how existing generations are MEASURED
    /// (which judges, which evaluation block, which rubric, which human
    /// labels) or how stages are CHAINED (the pipeline declaration).
    /// Measurement verbs (evaluate/analyze/rescore) may tolerate drift
    /// confined to these — loudly, and stamped — because the scientific
    /// object the guard protects (generations interpreted under the settings
    /// that produced them) is untouched by them. Observed need 2026-08-05: a
    /// study's pinned judge model died at its provider between run and
    /// evaluate, and the guard then demanded a full GPU re-run to judge
    /// generations the edit could not have affected. `promote` never
    /// tolerates: a judge swap changes what a judged sweep's evidence means.
    ///
    /// Identical list to the server's `run_epoch.MEASUREMENT_FIELDS`; the
    /// names are the manifest's JSON keys, and
    /// `withoutMeasurementFields` clears exactly these properties.
    ///
    /// `evaluationSampling` joined on 2026-08-29 (review round 12) and is the
    /// clearest member of the list: it chooses WHICH of a completed run's
    /// records get judged, so it cannot have moved a byte of that run's
    /// generations. It has to be here for the house's own flow to work —
    /// judged re-measurement runs on a never-frozen DUPLICATE, and a
    /// duplicate that declares the coding design differs from the original
    /// run's snapshot by exactly this key.
    public static let measurementFields = [
        "judges", "evaluation", "pipeline", "judgeRubricFile",
        "judgeRubricHash", "humanValidation", "evaluationSampling",
    ]

    /// The manifest reduced to its generation-side surface — the comparison
    /// object for the measurement-drift tolerance. Server twin:
    /// `_without_measurement_fields`.
    ///
    /// `name` is BLANKED on both sides, not listed in `measurementFields`:
    /// it is identity, not a measurement setting — but by the tolerance's
    /// own rule (a field that cannot have affected a byte of the source
    /// run's generations) a rename is tolerable on measurement verbs.
    /// Without this, the sanctioned duplicate-never-edit path (duplicate a
    /// study, pin a new rubric and panel, evaluate against the ORIGINAL
    /// run) refused on the one field the duplication itself must change
    /// (observed 2026-08-28, the calibration duplicate of a draft study).
    /// `promote` still refuses a renamed manifest: only measurement verbs
    /// pass `tolerateMeasurementDrift`.
    static func withoutMeasurementFields(
        _ manifest: ExperimentManifest
    ) -> ExperimentManifest {
        var copy = manifest
        copy.name = ""
        copy.judges = nil
        copy.evaluation = nil
        copy.pipeline = nil
        copy.judgeRubricFile = nil
        copy.judgeRubricHash = nil
        copy.humanValidation = nil
        copy.evaluationSampling = nil
        return copy
    }

    /// The changed-fields description when live and snapshot differ ONLY in
    /// `measurementFields`, else nil (the drift touches generation-side
    /// settings and must refuse). Server twin: `_measurement_drift`.
    static func measurementDrift(
        live: ExperimentManifest?, snapshot: ExperimentManifest?
    ) -> String? {
        guard let live, let snapshot else { return nil }
        guard
            ExperimentStore.manifestHash(withoutMeasurementFields(live))
                == ExperimentStore.manifestHash(
                    withoutMeasurementFields(snapshot))
        else { return nil }
        let summary = ManifestDiff.summary(snapshot, live)
        return summary.isEmpty ? "measurement-side fields differ" : summary
    }

    /// The live manifest re-pinned with the run snapshot's model revision —
    /// or nil when that repair does not apply.
    ///
    /// The run stage pins the resolved revision into a draft manifest, but
    /// bundle re-imports overwrite the live file with the bundle's unpinned
    /// copy — so a run's snapshot can carry the pinned epoch while the live
    /// manifest is the same manifest one write behind its own machinery
    /// (observed 2026-08-05: a completed 2-hour pipeline refused its own
    /// continuation over exactly this). A live manifest that LACKS a pin the
    /// snapshot has gets compared WITH that pin; a live manifest with a
    /// DIFFERENT pin is real drift and is not touched. Server twin:
    /// `_with_snapshot_revision`.
    static func withSnapshotRevision(
        live: ExperimentManifest?, snapshot: ExperimentManifest?
    ) -> ExperimentManifest? {
        guard var repinned = live, let snapshot else { return nil }
        guard (repinned.modelRevision ?? "").isEmpty else { return nil }
        guard let revision = snapshot.modelRevision, !revision.isEmpty else {
            return nil
        }
        repinned.modelRevision = revision
        return repinned
    }

    /// The strict check — the promote contract. A measurement-side edit
    /// changes what a judged sweep's evidence MEANS, so promote never
    /// tolerates drift; only measurement verbs pass
    /// `tolerateMeasurementDrift: true`.
    public static func refusal(
        verb: String,
        experiment: String,
        liveHash: String,
        runDirectory: URL,
        liveManifest: ExperimentManifest? = nil,
        allowUnverified: Bool = false
    ) -> String? {
        check(
            verb: verb, experiment: experiment, liveHash: liveHash,
            runDirectory: runDirectory, liveManifest: liveManifest,
            allowUnverified: allowUnverified,
            tolerateMeasurementDrift: false
        ).refusal
    }

    /// The refusal a MEASUREMENT verb gives a run produced on the other
    /// engine. Byte-identical to the server's
    /// `run_epoch.foreign_substrate_refusal`.
    ///
    /// Kept as its own composer (rather than inlined) so both engines' tests
    /// can assert the same sentence without a run directory.
    public static func foreignSubstrateRefusal(
        verb: String, runName: String, substrate: String
    ) -> String {
        "\(verb): source run '\(runName)' was produced on \(substrate), and "
            + "\(verb) reads that run's own records — record schemas and "
            + "pairing keys are per-engine, so measuring them here reports an "
            + "empty result as a success. Run \(verb) on the engine that "
            + "produced the run"
    }

    /// Check a source run against the live manifest epoch. Cross-engine twin
    /// of `run_epoch.epoch_refusal`; the semantics ARE the contract, so any
    /// change here belongs in both engines on the same day.
    ///
    /// `refuseForeignSubstrate` is what separates the two families of caller,
    /// and it exists because the snapshot rescue below is right for one of
    /// them and wrong for the other (WP0 dry run #2's P0):
    ///
    /// - `promote` reads only the run's SELECTION metadata, which is
    ///   engine-neutral JSON, and a cluster workspace's every sweep is
    ///   foreign — so it must accept a foreign run whose manifest snapshot
    ///   re-hashes to this engine's live hash. It passes `false`.
    /// - `analyze`/`evaluate`/`rescore-style` read the run's RECORDS, whose
    ///   schema and pairing keys are per-engine (Swift pairs on
    ///   `(seed, promptID)`, the server on `(promptID, sampleIndex)` with a
    ///   seed derived per condition) — so a foreign run read here silently
    ///   produces no pairs and reports the empty result as a success. They
    ///   pass `true`, and the snapshot rescue never gets to speak for them.
    public static func check(
        verb: String,
        experiment: String,
        liveHash: String,
        runDirectory: URL,
        liveManifest: ExperimentManifest? = nil,
        allowUnverified: Bool = false,
        tolerateMeasurementDrift: Bool = false,
        refuseForeignSubstrate: Bool = false
    ) -> Check {
        let runName = runDirectory.lastPathComponent
        // FIRST, and before any stamp is read: a foreign run's stamp is not
        // comparable, and for a measurement verb the snapshot rescue below
        // would answer the wrong question — whether the SETTINGS match, when
        // what fails is reading the RECORDS. `allowUnverifiedEpoch` does not
        // reach it either: that flag forgives a missing stamp, not a
        // substrate this engine cannot read.
        if refuseForeignSubstrate, let foreign = foreignSubstrate(runDirectory) {
            return Check(
                refusal: foreignSubstrateRefusal(
                    verb: verb, runName: runName, substrate: foreign))
        }
        guard let stamped = stampedExperimentHash(runDirectory) else {
            if allowUnverified { return Check(unverified: true) }
            return Check(
                refusal: "\(verb): source run '\(runName)' carries no "
                    + "experiment-hash stamp, so it cannot be proven to belong "
                    + "to the current manifest of '\(experiment)' (hash "
                    + "\(liveHash)) — re-run under the current manifest, or "
                    + "pass allowUnverifiedEpoch for legacy unstamped runs")
        }
        guard stamped != liveHash else { return .eligible }
        // A run stamped before `createdAt` left the hash canonicalization
        // (2026-08-17) carries the legacy hash of the SAME manifest — accept
        // exactly what the old comparison accepted, nothing wider.
        if let live = liveManifest,
            stamped == ExperimentStore.legacyManifestHash(live)
        {
            return .eligible
        }
        // Name the real cause when the run came from the OTHER engine. Epoch
        // hashes are per-engine by design (canonicalization differs), so a
        // foreign-substrate run ALWAYS mismatches — and a message blaming "a
        // different manifest epoch" sends the researcher hunting for a
        // manifest change that never happened.
        //
        // A foreign stamp is not evidence of a different epoch — it is no
        // evidence at all, because the hashes were never comparable. The run
        // carries its own manifest SNAPSHOT, so re-hash THAT with this
        // engine's function and compare like with like. This is the pattern
        // the validate-evidence matcher has used since 2026-07-21
        // (`ExperimentStore.validationEvidence`); promote's guard simply
        // never adopted it, and rejected legitimate cluster evidence on a
        // comparison that could not have succeeded (observed live
        // 2026-07-26 in a cluster workspace whose every sweep is foreign).
        let foreign = foreignSubstrate(runDirectory)
        // A condition THIS run projected (selection.sweepRun == its own
        // name) is the run's completion, not a different epoch: the sweep
        // writes `<concept>-recommended` after its start-time snapshot, and
        // the Mac adopts the same projection into the local draft — the
        // guard was refusing the exact state the run itself produced (field
        // incident 2026-08-04). Server twin: `_without_self_projected`.
        let strippedLive = liveManifest.map {
            withoutSelfProjectedConditions($0, runName: runName)
        }
        let strippedSnapshot = snapshot(runDirectory).map {
            withoutSelfProjectedConditions($0, runName: runName)
        }
        let liveComparableHash =
            strippedLive.map(ExperimentStore.manifestHash) ?? liveHash
        /// The run's own revision pin, clobbered from the live manifest by a
        /// bundle re-import — same epoch, one write behind.
        func revisionRepairMatches() -> Bool {
            guard
                let snap = strippedSnapshot,
                let repinned = withSnapshotRevision(
                    live: strippedLive, snapshot: snap)
            else { return false }
            return ExperimentStore.manifestHash(snap)
                == ExperimentStore.manifestHash(repinned)
        }
        /// Tolerated measurement-side drift, when this verb tolerates it.
        func toleratedDrift() -> Check? {
            guard tolerateMeasurementDrift,
                let drift = measurementDrift(
                    live: strippedLive, snapshot: strippedSnapshot)
            else { return nil }
            return Check(measurementDrift: drift)
        }
        if foreign != nil {
            guard let snap = strippedSnapshot else {
                return Check(
                    refusal: "\(verb): source run '\(runName)' was produced on "
                        + "\(foreign ?? "another engine") and carries no "
                        + "manifest snapshot, so there is no engine-neutral way "
                        + "to check it against '\(experiment)' — epoch stamps "
                        + "themselves do not cross substrates. Run \(verb) on "
                        + "the engine that produced the run")
            }
            if ExperimentStore.manifestHash(snap) == liveComparableHash {
                return .eligible
            }
            if revisionRepairMatches() { return .eligible }
            if let tolerated = toleratedDrift() { return tolerated }
            return Check(
                refusal: "\(verb): '\(experiment)' has changed since source "
                    + "run '\(runName)' was produced"
                    + changedFields(live: strippedLive, snapshot: snap)
                    + " — the run's settings are not the study's current "
                    + "settings")
        }
        if let live = strippedLive, let snap = strippedSnapshot,
            ExperimentStore.manifestHash(live)
                == ExperimentStore.manifestHash(snap)
        {
            // Same-substrate self-projection tolerance: the hashes differ
            // only by conditions this run itself projected.
            return .eligible
        }
        if revisionRepairMatches() { return .eligible }
        if let tolerated = toleratedDrift() { return tolerated }
        return Check(
            refusal: "\(verb): '\(experiment)' has changed since source run "
                + "'\(runName)' was produced"
                + changedFields(live: strippedLive, snapshot: strippedSnapshot)
                + " (run hash \(stamped), study now \(liveHash)) — the run "
                + "belongs to a different manifest epoch. Re-run under the "
                + "current manifest, or pass allowUnverifiedEpoch for legacy "
                + "unstamped runs")
    }

    /// Server twin: `run_epoch._without_self_projected`.
    static func withoutSelfProjectedConditions(
        _ manifest: ExperimentManifest, runName: String
    ) -> ExperimentManifest {
        var copy = manifest
        copy.conditions.removeAll { $0.selection?.sweepRun == runName }
        // Presentation-classifier normalization (field incident 2026-08-04,
        // second refusal): the Studies panel stamps `studyType` on drafts
        // when the study is merely OPENED — absent and declared-as-derived
        // mean the same study, so both sides compare at the canonical
        // value. A genuinely different declared type still refuses.
        copy.studyType = StudyIntent.derive(from: copy).rawValue
        return copy
    }

    /// The run's recorded substrate when it differs from this engine's.
    public static func foreignSubstrate(_ runDirectory: URL) -> String? {
        guard
            let data = try? Data(
                contentsOf: runDirectory.appending(component: "config.json")),
            let object = try? JSONSerialization.jsonObject(with: data)
                as? [String: Any],
            let substrate = object["substrate"] as? String,
            substrate != RepEReader.substrate
        else { return nil }
        return substrate
    }

    /// The `: fieldA: x → y; fieldB: …` clause naming what actually changed,
    /// or "" when the manifests are unavailable to compare. A refusal that
    /// only prints two hashes leaves `--force` as the sole next move.
    static func changedFields(
        live: ExperimentManifest?, snapshot: ExperimentManifest?
    ) -> String {
        guard let live, let snapshot else { return "" }
        let summary = ManifestDiff.summary(snapshot, live)
        return summary.isEmpty ? "" : ": " + summary
    }
}
