import Foundation
import Testing

@testable import ExperimentKit

/// B3 — a server-promoted agent must be usable on the Mac after import.
///
/// The live failure (2026-07-26): a `neuroticism` agent promoted on the
/// cluster listed under the server's own Agents panel but never appeared in
/// the local Agent Library, so it could not be selected in Studies. Two
/// independent causes, both fixed here:
///
/// 1. **Layout.** The engines file agents differently —
///    `runs/model-variants/<slug>/model-variant.json` (Swift) vs
///    `runs/<stamp>-variant-<name>/<name>.json` (Python) — and discovery
///    matched only the first, by literal filename.
/// 2. **Path shape.** `promote` writes `vectorArtifactID` workspace-relative;
///    Swift compared it verbatim against absolute catalog ids and opened it
///    with `URL(filePath:)`, i.e. against the process working directory.
///
/// The server-shaped fixture here is GENERATED BY THE PYTHON ENGINE
/// (`scripts/regenerate-cross-engine-fixtures.py` → `Tests/Fixtures/
/// cross-engine/server-minted-agent.json`), not hand-written — see
/// `ServerFixture` for why that distinction is the whole point.
struct ImportedAgentDiscoveryTests {

    private func withWorkspace<T>(_ body: (URL) throws -> T) rethrows -> T {
        let temp = FileManager.default.temporaryDirectory
            .appending(component: "imported-agents-\(UUID().uuidString)")
        try? FileManager.default.createDirectory(
            at: temp, withIntermediateDirectories: true)
        ExperimentRootOverrideLock.acquire()
        WorkspaceRoot.programmaticOverride = temp
        defer {
            WorkspaceRoot.programmaticOverride = nil
            ExperimentRootOverrideLock.release()
            try? FileManager.default.removeItem(at: temp)
        }
        return try body(temp)
    }

    /// The Python engine's ACTUAL output, committed by
    /// `scripts/regenerate-cross-engine-fixtures.py`.
    ///
    /// Reading the real producer's bytes is the point (B1). A Swift test that
    /// hand-writes what it believes the server emits pins the Swift author's
    /// belief, not the server's behaviour — and both bugs this file covers
    /// were exactly that belief drifting out of date. Now a server-side
    /// layout change shows up as a fixture diff in review.
    private struct ServerFixture {
        var runDirectorySuffix: String
        var artifactFileName: String
        var configRunType: String
        var artifact: [String: Any]

        static func load() throws -> ServerFixture {
            let url = CodeResources.compiledCheckoutPath.appending(
                components: "Tests", "Fixtures", "cross-engine",
                "server-minted-agent.json")
            let object = try JSONSerialization.jsonObject(
                with: try Data(contentsOf: url)) as? [String: Any]
            let root = try #require(object)
            return .init(
                runDirectorySuffix: try #require(
                    root["runDirectorySuffix"] as? String),
                artifactFileName: try #require(
                    root["artifactFileName"] as? String),
                configRunType: try #require(root["configRunType"] as? String),
                artifact: try #require(root["artifact"] as? [String: Any]))
        }

        /// Rebuild the server's on-disk shape inside a local workspace,
        /// exactly as evidence import would land it.
        @discardableResult
        func plant(in workspace: URL, stamp: String = "20260726T000000000")
            throws -> URL
        {
            let runDirectory = workspace.appending(
                components: "runs", stamp + runDirectorySuffix)
            try FileManager.default.createDirectory(
                at: runDirectory, withIntermediateDirectories: true)
            let config: [String: Any] = [
                "schemaVersion": 2, "runType": configRunType,
                "modelID": artifact["baseModelID"] as? String ?? "",
                "createdAt": "2026-07-26T00:00:00Z",
            ]
            try JSONSerialization.data(withJSONObject: config)
                .write(to: runDirectory.appending(component: "config.json"))
            let url = runDirectory.appending(component: artifactFileName)
            try JSONSerialization.data(
                withJSONObject: artifact, options: [.sortedKeys]
            ).write(to: url)
            return url
        }
    }

    @Test func serverMintedAgentsAppearInTheLocalLibrary() throws {
        let fixture = try ServerFixture.load()
        try withWorkspace { workspace in
            try fixture.plant(in: workspace)

            let found = ModelVariantStore.scan()
            #expect(found.count == 1)
            #expect(found.first?.artifact.name == "neuroticism-agent")
            // The reference the server actually wrote is workspace-RELATIVE.
            #expect(
                found.first?.artifact.injections.first?.vectorArtifactID
                    .hasPrefix("runs/") == true)
        }
    }

    /// Guard on the fixture itself: if the server ever files agents the way
    /// Swift does, the second discovery pass becomes dead code and this test
    /// says so rather than silently passing forever.
    @Test func theTwoEnginesStillUseDifferentLayouts() throws {
        let fixture = try ServerFixture.load()
        #expect(fixture.artifactFileName != "model-variant.json")
        #expect(fixture.configRunType == "variant-save")
        #expect(fixture.runDirectorySuffix.contains("-variant-"))
    }

    @Test func theNativeLibraryLayoutStillScans() throws {
        try withWorkspace { workspace in
            // Regression guard: the second pass must not cost the first.
            let library = workspace.appending(
                components: "runs", "model-variants", "fear-agent")
            try FileManager.default.createDirectory(
                at: library, withIntermediateDirectories: true)
            let artifact: [String: Any] = [
                "name": "fear-agent", "baseModelID": "test/model",
                "createdAt": "2026-07-25T00:00:00Z", "bandWidth": 1,
                "alphaInNormUnits": true, "injections": [], "adapters": [],
            ]
            try JSONSerialization.data(withJSONObject: artifact, options: [.sortedKeys])
                .write(to: library.appending(component: "model-variant.json"))

            #expect(ModelVariantStore.scan().map(\.artifact.name) == ["fear-agent"])
        }
    }

    @Test func bothLayoutsCoexistAndAreNotDoubleCounted() throws {
        try withWorkspace { workspace in
            try ServerFixture.load().plant(in: workspace)
            let library = workspace.appending(
                components: "runs", "model-variants", "fear-agent")
            try FileManager.default.createDirectory(
                at: library, withIntermediateDirectories: true)
            let artifact: [String: Any] = [
                "name": "fear-agent", "baseModelID": "test/model",
                "createdAt": "2026-07-25T00:00:00Z", "bandWidth": 1,
                "alphaInNormUnits": true, "injections": [], "adapters": [],
            ]
            try JSONSerialization.data(withJSONObject: artifact, options: [.sortedKeys])
                .write(to: library.appending(component: "model-variant.json"))

            let names = ModelVariantStore.scan().map(\.artifact.name)
            #expect(names.count == 2)
            #expect(Set(names) == ["neuroticism-agent", "fear-agent"])
            // Newest first.
            #expect(names.first == "neuroticism-agent")
        }
    }

    @Test func aRunDirectoryWithoutTheVariantStampIsNotAnAgent() throws {
        try withWorkspace { workspace in
            // An ordinary extract run also contains .json files; only the
            // canonical runType stamp makes a directory an agent mint.
            let runDirectory = workspace.appending(
                components: "runs", "20260726T000000000-extract")
            try FileManager.default.createDirectory(
                at: runDirectory, withIntermediateDirectories: true)
            let config: [String: Any] = [
                "schemaVersion": 2, "runType": "extract", "modelID": "test/model",
            ]
            try JSONSerialization.data(withJSONObject: config)
                .write(to: runDirectory.appending(component: "config.json"))
            let sidecar: [String: Any] = [
                "name": "neuroticism", "baseModelID": "test/model",
                "createdAt": "2026-07-26T00:00:00Z", "bandWidth": 1,
                "alphaInNormUnits": true, "injections": [], "adapters": [],
            ]
            try JSONSerialization.data(withJSONObject: sidecar, options: [.sortedKeys])
                .write(to: runDirectory.appending(component: "neuroticism.json"))

            #expect(ModelVariantStore.scan().isEmpty)
        }
    }

    // MARK: path-shape tolerance

    @Test func aRelativeReferenceMatchesAnAbsoluteCatalogID() throws {
        try withWorkspace { workspace in
            let absolute = workspace
                .appending(components: "runs", "extract-1", "neuroticism")
                .standardizedFileURL.path
            let artifact = ModelVariantArtifact(
                name: "neuroticism", baseModelID: "test/model",
                injections: [
                    .init(
                        concept: "neuroticism",
                        vectorArtifactID: "runs/extract-1/neuroticism",
                        layer: 41, alpha: 0.1)
                ],
                promptMode: "chat", qwenThinkingEnabled: false,
                temperature: 0, systemPrompt: "")
            let availability = AgentLibrary.Availability(
                localModelIDs: ["test/model"],
                localVectorIDs: [absolute])

            // Before B3 this reported the agent as missing its vector
            // however many times the vector was imported.
            #expect(AgentLibrary.missingVectorRefs(artifact, availability: availability).isEmpty)
            #expect(AgentLibrary.isRunnableLocally(artifact, availability: availability))
        }
    }

    @Test func aGenuinelyAbsentVectorIsStillReportedMissing() throws {
        try withWorkspace { _ in
            let artifact = ModelVariantArtifact(
                name: "neuroticism", baseModelID: "test/model",
                injections: [
                    .init(
                        concept: "neuroticism",
                        vectorArtifactID: "runs/extract-1/neuroticism",
                        layer: 41, alpha: 0.1)
                ],
                promptMode: "chat", qwenThinkingEnabled: false,
                temperature: 0, systemPrompt: "")
            let availability = AgentLibrary.Availability(
                localModelIDs: ["test/model"],
                localVectorIDs: ["/somewhere/else/fear"])
            #expect(
                AgentLibrary.missingVectorRefs(artifact, availability: availability)
                    == ["runs/extract-1/neuroticism"])
            #expect(!AgentLibrary.isRunnableLocally(artifact, availability: availability))
        }
    }
}
